### ISSUE TITLE
Add a postinstall hook to warn when installing via CLI

### ISSUE THREAD

**Issue by jesstelford** [npm/security-holder#1]
I'm thinking a warning similar to unmet peer deps - something that doesn't break the build, but gives the user a fair warning that things probably aren't how they expect.

**Comment by aredridel** [comment]
Or a deprecation set on the package would be good.

**Comment by peabnuts123** [comment]
These are good ideas. Any traction on getting some more visibility of installing the Security Holder package?

**Comment by despossivel** [comment]
Sorry for the problems. The project is still new and I'm reviewing some bugs that affect how the tool works. I will be making the source code available soon after the refactoring so that the community can collaborate to make the clip stable.

**Comment by DanielRuf** [comment]
A warning is often not sufficient as these will be silently ignored on CI and normal installs as these throw no error but should be raised to one as removed or replaced packages might break things and security is something critical.

In my opinion we should be more strict.
See https://github.com/DanielRuf/security-holding-package/blob/master/index.js for an approach that I would recommend.
