### ISSUE TITLE
If this package is not currently in use then what is?

### ISSUE THREAD

**Issue by rsegecin** [npm/security-holder#10]
I'd like to use the package fs that I believe stands for file system and npm's site is pointing that here's the repository for this package. That on Readme it says "This package name is not currently in use" but I've seen many resources using this package. So if this repo is deprecated what's the one that should be used instead of? I new on the nodejs scene could anyone please enlight me in this confusion.

**Comment by tdmalone** [comment]
Hi @rsegecin,

fs is built in to Node, so you don’t need to install a separate package. The name fs on npm is just a placeholder to avoid conflicts.

Requiring fs in your JS will work as you expect without needing installation.

See https://nodejs.org/api/fs.html for full documentation.

**Comment by rsegecin** [comment]
Thank you to clarify that tdmalone. So the package not currently in using is referring just to a package called "Security holding"?

**Comment by tdmalone** [comment]
Yes, it's just a placeholder. You can safely ignore it. npm doesn't host anything to do with `fs` :)

**Comment by rsegecin** [comment]
Thank you very much.
