### ISSUE TITLE
node webkit 0.14.7 application is crashing when we use child_process in offline mode

### ISSUE THREAD

**Issue by GeethaG** [npm/security-holder#11]
@isaacs  Can any one provide the workaround or replacement for child_process node module which work offline

**Comment by GeethaG** [comment]
Can anyone please respond to this asap.

**Comment by MKRhere** [comment]
What are you even trying to do? If you reached here from an npm package's GitHub link, then unfortunately that npm package was taken down, and is no longer available. You should not try to use this in your project.

**Comment by GeethaG** [comment]
Thank you for your response. My issue is resolved and I am no longer using the child_process node module in my project.
