### ISSUE TITLE
Unexpected key 'Key' found in params when deleting a file from S3

### ISSUE THREAD

**Issue by xargr** [npm/security-holder#12]
I have version:

`"strapi-upload-aws-s3": "^3.0.0-alpha.14.3"`

when I try to delete any file one error appear:

`MissingRequiredParameter: Missing required key 'Delete' in params
UnexpectedParameter: Unexpected key 'Key' found in params`

**Comment by rosswilson** [comment]
@xargr the `strapi-upload-aws-s3` NPM package has been removed from the registry. See https://www.npmjs.com/package/strapi-upload-aws-s3.

When a package is removed, sometimes the NPM team will replace it with this repo, explaining what's going on. That's why you're seeing errors.
