### ISSUE TITLE
very confused what this is

### ISSUE THREAD

**Issue by zmitton** [npm/security-holder#14]
I'm trying to use the node native object `fs` for file handling. In my mocha tests it says it cant find `fs`. However, in the file, using `fs`, if I declare `fs = require('fs')` is works....

This confuses me because I also dont even have the `fs` package installed or declared in my `package.json` file.

So I went to npmjs.com to see what the hell the package may look like.

Then I see the code is empty! the message says its a placeholder! and yet is has hundreds of thousands of downloads???!!

Does anyone know why my code is acting the way it is or the best way to go about using `fs` (the native node one) in a package?

**Comment by ScottRudiger** [comment]
You've likely figured this out by now (and this is hardly the place for this question), but [`fs` is a native Node.js module](https://nodejs.org/api/fs.html).

There's no need to install it; in fact, you can see that by the way you declared
`const fs = require('fs);`.

**Comment by AndrewDavis** [comment]
Put that in the README you dorps

**Comment by jakebellacera** [comment]
@AndrewDavis this package is used for many protected packages, not just `fs`, so I think the existing README suffices.

**Comment by zmitton** [comment]
ok so in conclusion, I have to use the `require` statement even for (some?) native modules in Node.js
