### ISSUE TITLE
Build Broken

### ISSUE THREAD

**Issue by dalesthillaire** [npm/security-holder#16]
Any ideas why our application build is broken here? According to the docs for this repo, I understand this to just be a placeholder. How do I find a suitable replacement for former package. 

![image](https://user-images.githubusercontent.com/33377318/66615402-87f54580-eb9a-11e9-820c-7e9ee1da9b7b.png)
![image](https://user-images.githubusercontent.com/33377318/66615411-980d2500-eb9a-11e9-975d-eb8b91e546b7.png)

**Comment by Slumber86** [comment]
Just delete it, it's useless
