### ISSUE TITLE
[QUESTION] Claim/Recover a package

### ISSUE THREAD

**Issue by bsysop** [npm/security-holder#20]
# What / Why

> I had multiple packages, I was holding this waiting for the company investigation, they want to transfer this to them again, how can proceed in this case? Thank you!.

## Where

* Multiple

## Who

* sutexago

## References

* n/a

**Comment by bigkatspence** [comment]
> # What / Why
> > I had multiple packages, I was holding this waiting for the company investigation, they want to transfer this to them again, how can proceed in this case? Thank you!.
> 
> ## Where
> * Multiple
> 
> ## Who
> * sutexago
> 
> ## References
> * n/a

Merge#20 with #

**Comment by orlyjamie** [comment]
Agreed, I'm in the same boat, was holding onto a package for a partner/client to prevent it being maliciously registered as part of a dependency confusion attack. 

How to reclaim this?
