### ISSUE TITLE
missing index.js

### ISSUE THREAD

**Issue by Cypria** [npm/security-holder#7]
you've got a missing index.js. I thought it would be an npm problem but here it isnt either.

**Comment by xshotD** [comment]
This doesn't need a index.js

**Comment by NdT3Development** [comment]
This does not need to have an index.js (or any .js files) as it is not actually a package that should be downloaded. It is a placeholder for packages taken down from npm due to previous malicious use of the package name.

**Comment by daniloster** [comment]
So, how could I handle the reference pointed out by package.json `"main": "index.js",`?
Because, once it is being bundled using webpack it is not find the module. Could anyone give me a hand? Thanks

**Comment by graingert** [comment]
@daniloster can you post your package.json?

**Comment by graingert** [comment]
@daniloster you really shouldn't try to install a security-holder package

**Comment by bidetaggle** [comment]
If I understand well, a security-holder package is executed from npm servers where the index.js is through node with public APIs ?

**Comment by graingert** [comment]
@bidetaggle no that's not right

**Comment by tilda** [comment]
This issue should be closed as the package.json does not refer to index.js anymore

**Comment by bidetaggle** [comment]
Where can I download and read fs package ?

**Comment by graingert** [comment]
@bidetaggle the fs module is already built into node. You don't need or want to download it from npm

**Comment by graingert** [comment]
@bidetaggle https://github.com/nodejs/node/blob/master/lib/fs.js
